[Kind]
authors = ["NaoEhSavio", "Bonatto"]
language = "EN"
multilingual = false
src = "Kind/src"
title = "Kind"

[build]
build-dir = "../docs/Kind"
use-default-preprocessors = false

[preprocessor.index]

[preprocessor.links]

[output.html]
mathjax-support = true