[Kind]
authors = ["NaoEhSavio", "Bonatto"]
language = "pt-BR"
multilingual = false
src = "ptBR/src"
title = "Kind pt-BR"

[build]
build-dir = "../../docs/Kind-ptBR"
use-default-preprocessors = false

[preprocessor.index]

[preprocessor.links]

[output.html]
mathjax-support = true