[Lang]
language = "en"
multilingual = false
src = "Lang/src"
title = "Lang"

[build]
build-dir = "../docs/Lang"
use-default-preprocessors = false

[preprocessor.index]

[preprocessor.links]

[output.html]
mathjax-support = true